### ISSUE TITLE
データがダウンロードできなくなっていて利用できません

### ISSUE THREAD

**Issue by mnagaku** [funalab/ExperimentalMedicine2020#1]
https://fun.bio.keio.ac.jp/~tokuoka/Downloads/datasets.tar.gz
https://fun.bio.keio.ac.jp/~tokuoka/Downloads/inference_model

データ2つが404notFoundでダウンロードできないため、ノートブックを正しく利用することができません。

**Comment by funasoul** [comment]
ありがとうございます。
今朝方、ラボのwebサーバを入れ替えたのですが rewrite rule がまだ正しく動作していないようです。とりあえずコードが動作するよう修正しました。
ご確認ください。

**Comment by mnagaku** [comment]
早速のご対応ありがとうございます。データをダウンロードして、ノートブックを最後まで動かせました。
